from measure_zero_package.exceptions.tuple_list_exception import TupleListError